name: Publish new Release
#on: [push]
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Check that can be compiled
      run: go build -v cmd/cli-transcoder/cli-transcoder.go

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    name: Build
    runs-on: ubuntu-latest
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     # os: [macos-latest, ubuntu-latest]
    #     os: [macos-latest, windows-latest, ubuntu-latest]
    needs: create_release
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        make cli-transcoder
        tar -czvf cli-transcoder.linux.amd64.tar.gz cli-transcoder
        GOOS=linux GOARCH=arm make cli-transcoder
        tar -czvf cli-transcoder.linux.arm32.tar.gz cli-transcoder
        GOOS=linux GOARCH=arm64 make cli-transcoder
        tar -czvf cli-transcoder.linux.arm64.tar.gz cli-transcoder
        GOOS=darwin GOARCH=arm64 make cli-transcoder
        tar -czvf cli-transcoder.macos.arm64.tar.gz cli-transcoder
        GOOS=darwin GOARCH=amd64 make cli-transcoder
        tar -czvf cli-transcoder.macos.amd64.tar.gz cli-transcoder
        GOOS=windows GOARCH=amd64 make cli-transcoder
        tar -czvf cli-transcoder.windows.amd64.tar.gz cli-transcoder.exe

    - name: Release Posix
      uses: softprops/action-gh-release@v1
      with:
        files: |
            cli-transcoder.linux.amd64.tar.gz
            cli-transcoder.linux.arm32.tar.gz
            cli-transcoder.linux.arm64.tar.gz
            cli-transcoder.macos.amd64.tar.gz
            cli-transcoder.macos.arm64.tar.gz
            cli-transcoder.windows.amd64.tar.gz
          # body_path: ${{ github.workflow }}-CHANGELOG.txt
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

